module.exports = {
    DEFAULT_MILLISECONDS: 20000,
    DEFAULT_MILLISECONDS_PAUSE: 5000,
    USER_PASSWORD: '123asd',
    USER_NEW_PASSWORD: '123asdf',
    ORGANIZATION_KEY: 'key05',
    LOCATION_KEY: 'key06',
    LOCATION_ADDRESS: 'Adress',
    ORGANIZATION_KEY: 'key01',
    LOCATION_ADDRESS: 'testAddress',
    DEFAULT_LOCATION_KEY: 'key02',
    NEW_LOCATION_KEY: 'key03',
    USER_FOR_ADD_EMAIL: 'noka@abv.bg',
    SECOND_USER_EMAIL: 'ellyval@gmail.com',
    USER_FOR_REGISTER: 'nikola_andreev@students.softuni.bg',
    MAIN_URL: 'https://local.a4everyone.com',
    ORGANIZATIONS_URL: 'https://local.a4everyone.com/user/organizations/',
    APPS_URL: 'https://local.a4everyone.com/user/apps/',
    SETTINGS_URL: 'https://local.a4everyone.com/user/settings/'
}